/**
 * Post-generation script to transform primitive types to TON types
 *
 * Strategy:
 * 1. Parse api.yml to find all fields with special formats
 * 2. Create a mapping of field types
 * 3. Modify generated types.gen.ts based on this mapping
 */

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';

const ROOT_DIR = process.cwd();
const API_SPEC_PATH = path.join(ROOT_DIR, 'src', 'api.yml');
const TYPES_FILE = path.join(ROOT_DIR, 'src', 'generated', 'types.gen.ts');

interface TypeReplacement {
  from: string;
  to: string;
}

/**
 * Parse OpenAPI spec and find all fields that need type replacement
 */
function analyzeSpec(spec: any): Map<string, string> {
  const typeMap = new Map<string, string>();

  function processSchema(schema: any, schemaName?: string) {
    if (!schema || typeof schema !== 'object') return;

    // Check if this schema itself needs replacement
    if (schema.type === 'string') {
      if (schema.format === 'address') {
        if (schemaName) {
          console.log(`  Found address field in schema: ${schemaName}`);
        }
        return 'Address';
      } else if (schema.format === 'cell' || schema.format === 'cell-base64') {
        if (schemaName) {
          console.log(`  Found cell field in schema: ${schemaName}`);
        }
        return 'Cell';
      } else if (schema['x-js-format'] === 'bigint') {
        if (schemaName) {
          console.log(`  Found bigint string field in schema: ${schemaName}`);
        }
        return 'bigint';
      }
    }

    if (schema.type === 'integer' && schema['x-js-format'] === 'bigint') {
      if (schemaName) {
        console.log(`  Found bigint integer field in schema: ${schemaName}`);
      }
      return 'bigint';
    }

    if (schema.type === 'object' && schema.format === 'tuple-item') {
      if (schemaName) {
        console.log(`  Found tuple-item field in schema: ${schemaName}`);
      }
      return 'TupleItem';
    }

    // Process properties
    if (schema.properties) {
      for (const [propName, propSchema] of Object.entries(schema.properties)) {
        const replacement = processSchema(propSchema, `${schemaName}.${propName}`);
        if (replacement) {
          typeMap.set(`${schemaName}.${propName}`, replacement);
        }
      }
    }

    // Process array items
    if (schema.items) {
      processSchema(schema.items, schemaName ? `${schemaName}[]` : undefined);
    }

    // Process allOf, anyOf, oneOf
    ['allOf', 'anyOf', 'oneOf'].forEach((key) => {
      if (Array.isArray(schema[key])) {
        schema[key].forEach((item: any) => processSchema(item, schemaName));
      }
    });

    // Process additionalProperties
    if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
      processSchema(schema.additionalProperties, schemaName);
    }

    return null;
  }

  // Process all schemas
  if (spec.components?.schemas) {
    console.log('\nAnalyzing OpenAPI spec for TON types...');
    for (const [schemaName, schema] of Object.entries(spec.components.schemas)) {
      processSchema(schema, schemaName);
    }
  }

  return typeMap;
}

/**
 * Transform generated types.gen.ts file
 */
function transformTypes(content: string): string {
  let transformed = content;
  let replacementCount = 0;

  // Add imports at the top (after auto-generated comment)
  const autoGenComment = '// This file is auto-generated by @hey-api/openapi-ts';
  if (transformed.includes(autoGenComment)) {
    transformed = transformed.replace(
      autoGenComment,
      `${autoGenComment}\n\nimport { Address, Cell, TupleItem } from '@ton/core';`
    );
    console.log('✓ Added @ton/core imports');
  }

  // Replace types based on context
  // Note: We need to be careful with regex patterns to match actual TypeScript syntax

  // 1. Replace address: string with address: Address
  // Match patterns like:  address: string; or  address?: string;
  const addressPattern = /(\s+address\??:\s*)string(;)/g;
  const addressMatches = transformed.match(addressPattern);
  if (addressMatches) {
    transformed = transformed.replace(addressPattern, '$1Address$2');
    replacementCount += addressMatches.length;
    console.log(`✓ Replaced ${addressMatches.length} address fields: string → Address`);
  }

  // 2. Replace boc and cell fields (Cell data)
  const bocPattern = /(\s+(?:boc|cell)\??:\s*)string(;)/g;
  const bocMatches = transformed.match(bocPattern);
  if (bocMatches) {
    transformed = transformed.replace(bocPattern, '$1Cell$2');
    replacementCount += bocMatches.length;
    console.log(`✓ Replaced ${bocMatches.length} boc/cell fields: string → Cell`);
  }

  // 3. Replace fields ending with _address: string
  const addressSuffixPattern = /(\s+\w*_address\??:\s*)string(;)/g;
  const addressSuffixMatches = transformed.match(addressSuffixPattern);
  if (addressSuffixMatches) {
    transformed = transformed.replace(addressSuffixPattern, '$1Address$2');
    replacementCount += addressSuffixMatches.length;
    console.log(`✓ Replaced ${addressSuffixMatches.length} *_address fields: string → Address`);
  }

  return transformed;
}

/**
 * Transform generated transformers.gen.ts to convert unix timestamps to Date
 *
 * @hey-api/transformers converts timestamp fields to BigInt by default.
 * We need to replace BigInt(timestamp) with new Date(timestamp * 1000) for unix timestamps.
 */
function transformTransformers(content: string): string {
  let transformed = content;
  let replacementCount = 0;

  // Unix timestamp fields that should be Date objects instead of BigInt
  const timestampFields = [
    'timestamp',
    'created_at',
    'updated_at',
    'last_activity',
    'expires_at',
    'valid_until',
    'start_from',
    'cycle_start',
    'cycle_end',
  ];

  // Replace BigInt conversions with Date conversions for timestamp fields
  // Pattern: data.timestamp = BigInt(data.timestamp.toString());
  // Replace with: data.timestamp = new Date(Number(data.timestamp) * 1000);

  for (const field of timestampFields) {
    // Match patterns like: data.timestamp = BigInt(data.timestamp.toString());
    const bigintPattern = new RegExp(
      `(\\s+)(data\\.${field} = )BigInt\\(data\\.${field}\\.toString\\(\\)\\);`,
      'g'
    );

    const matches = transformed.match(bigintPattern);
    if (matches) {
      transformed = transformed.replace(
        bigintPattern,
        `$1$2new Date(Number(data.${field}) * 1000);`
      );
      replacementCount += matches.length;
    }
  }

  if (replacementCount > 0) {
    console.log(`✓ Replaced ${replacementCount} unix timestamp BigInt → Date conversions`);
  }

  return transformed;
}

/**
 * Transform types.gen.ts to change timestamp field types from bigint to Date
 */
function transformTimestampTypes(content: string): string {
  let transformed = content;
  let replacementCount = 0;

  // Change timestamp types from bigint to Date
  const timestampFields = [
    'timestamp',
    'created_at',
    'updated_at',
    'last_activity',
    'expires_at',
    'valid_until',
    'start_from',
    'cycle_start',
    'cycle_end',
  ];

  for (const field of timestampFields) {
    // Pattern: timestamp: bigint; or timestamp?: bigint;
    const pattern = new RegExp(
      `(\\s+${field}\\??: )bigint(;)`,
      'g'
    );

    const matches = transformed.match(pattern);
    if (matches) {
      transformed = transformed.replace(pattern, '$1Date$2');
      replacementCount += matches.length;
    }
  }

  if (replacementCount > 0) {
    console.log(`✓ Changed ${replacementCount} timestamp types: bigint → Date`);
  }

  return transformed;
}

async function main() {
  console.log('🔧 Post-processing generated types...\n');

  const TRANSFORMERS_FILE = path.join(ROOT_DIR, 'src', 'generated', 'transformers.gen.ts');

  // Check if files exist
  if (!fs.existsSync(API_SPEC_PATH)) {
    console.error(`❌ API spec not found: ${API_SPEC_PATH}`);
    process.exit(1);
  }

  if (!fs.existsSync(TYPES_FILE)) {
    console.error(`❌ Types file not found: ${TYPES_FILE}`);
    process.exit(1);
  }

  // Parse OpenAPI spec
  const specContent = fs.readFileSync(API_SPEC_PATH, 'utf-8');
  const spec = yaml.parse(specContent);

  // Analyze spec (for debugging - we're not using the map yet)
  analyzeSpec(spec);

  // Transform types
  console.log('\nTransforming types.gen.ts...');
  let typesContent = fs.readFileSync(TYPES_FILE, 'utf-8');
  typesContent = transformTypes(typesContent);
  typesContent = transformTimestampTypes(typesContent);
  fs.writeFileSync(TYPES_FILE, typesContent, 'utf-8');

  // Transform transformers (add Date conversions)
  if (fs.existsSync(TRANSFORMERS_FILE)) {
    console.log('\nTransforming transformers.gen.ts...');
    const originalTransformersContent = fs.readFileSync(TRANSFORMERS_FILE, 'utf-8');
    const transformedTransformersContent = transformTransformers(originalTransformersContent);
    fs.writeFileSync(TRANSFORMERS_FILE, transformedTransformersContent, 'utf-8');
  } else {
    console.log('\n⚠️  transformers.gen.ts not found, skipping timestamp conversions');
  }

  console.log('\n✅ Post-processing complete!');
  console.log(`   Modified: ${TYPES_FILE}`);
  if (fs.existsSync(TRANSFORMERS_FILE)) {
    console.log(`   Modified: ${TRANSFORMERS_FILE}`);
  }
}

main().catch((error) => {
  console.error('❌ Post-processing failed:', error);
  process.exit(1);
});
